# Generated by Django 5.1.6 on 2025-04-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemmode_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
